
name: vertx-server CI docker

on:
  push:
    paths:
      - "backend/vertx-graph-server/**"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: rabisu/musu-social
        tags: node-server
        registry: docker.io
        dockerfile: backend/vertx-graph-server/Dockerfile
        directory: backend/vertx-graph-server/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
